# Generated by Django 2.1 on 2018-08-18 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productcategory',
            options={'verbose_name_plural': 'Product Categories'},
        ),
        migrations.AlterModelOptions(
            name='producttag',
            options={'verbose_name_plural': 'Product Tags'},
        ),
    ]
