# Generated by Django 2.1 on 2018-09-05 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0002_auto_20180818_1628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='is_active',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
