# Generated by Django 2.1 on 2018-09-17 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0004_auto_20180905_1607'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='product',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='user',
        ),
        migrations.AddField(
            model_name='order',
            name='cookie_id',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='state',
            field=models.CharField(default='CART', max_length=32),
        ),
        migrations.AlterField(
            model_name='product',
            name='photo',
            field=models.ImageField(default='product_pics/default.jpg', upload_to='product_pics/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
