# Generated by Django 2.1 on 2018-09-18 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0005_auto_20180917_2127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='state',
            field=models.CharField(choices=[('CART', 'On cart'), ('PRO', 'Processing'), ('CAN', 'Cancelled'), ('RET', 'Returned'), ('FIN', 'Finished')], default='CART', max_length=4),
        ),
    ]
